/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PastRouteImport } from './routes/past'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms/$roomId'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as JoinRoomIdRouteImport } from './routes/join.$roomId'
import { Route as RoomsRoomIdMatchesRouteImport } from './routes/rooms/$roomId_.matches'
import { Route as OrganizerRoomsNewRouteImport } from './routes/organizer/rooms.new'
import { Route as RoomsRoomIdMatchesPrintRouteImport } from './routes/rooms/$roomId_.matches_.print'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PastRoute = PastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoomIdRoute = JoinRoomIdRouteImport.update({
  id: '/join/$roomId',
  path: '/join/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdMatchesRoute = RoomsRoomIdMatchesRouteImport.update({
  id: '/rooms/$roomId_/matches',
  path: '/rooms/$roomId/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoomsNewRoute = OrganizerRoomsNewRouteImport.update({
  id: '/organizer/rooms/new',
  path: '/organizer/rooms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdMatchesPrintRoute = RoomsRoomIdMatchesPrintRouteImport.update({
  id: '/rooms/$roomId_/matches_/print',
  path: '/rooms/$roomId/matches/print',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/past': typeof PastRoute
  '/signup': typeof SignupRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/r/$code': typeof RCodeRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/organizer/rooms/new': typeof OrganizerRoomsNewRoute
  '/rooms/$roomId/matches': typeof RoomsRoomIdMatchesRoute
  '/rooms/$roomId/matches/print': typeof RoomsRoomIdMatchesPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/past': typeof PastRoute
  '/signup': typeof SignupRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/r/$code': typeof RCodeRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/organizer/rooms/new': typeof OrganizerRoomsNewRoute
  '/rooms/$roomId/matches': typeof RoomsRoomIdMatchesRoute
  '/rooms/$roomId/matches/print': typeof RoomsRoomIdMatchesPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/past': typeof PastRoute
  '/signup': typeof SignupRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/r/$code': typeof RCodeRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/organizer/rooms/new': typeof OrganizerRoomsNewRoute
  '/rooms/$roomId_/matches': typeof RoomsRoomIdMatchesRoute
  '/rooms/$roomId_/matches_/print': typeof RoomsRoomIdMatchesPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/past'
    | '/signup'
    | '/join/$roomId'
    | '/r/$code'
    | '/rooms/$roomId'
    | '/organizer/rooms/new'
    | '/rooms/$roomId/matches'
    | '/rooms/$roomId/matches/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/past'
    | '/signup'
    | '/join/$roomId'
    | '/r/$code'
    | '/rooms/$roomId'
    | '/organizer/rooms/new'
    | '/rooms/$roomId/matches'
    | '/rooms/$roomId/matches/print'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/past'
    | '/signup'
    | '/join/$roomId'
    | '/r/$code'
    | '/rooms/$roomId'
    | '/organizer/rooms/new'
    | '/rooms/$roomId_/matches'
    | '/rooms/$roomId_/matches_/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PastRoute: typeof PastRoute
  SignupRoute: typeof SignupRoute
  JoinRoomIdRoute: typeof JoinRoomIdRoute
  RCodeRoute: typeof RCodeRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  OrganizerRoomsNewRoute: typeof OrganizerRoomsNewRoute
  RoomsRoomIdMatchesRoute: typeof RoomsRoomIdMatchesRoute
  RoomsRoomIdMatchesPrintRoute: typeof RoomsRoomIdMatchesPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past': {
      id: '/past'
      path: '/past'
      fullPath: '/past'
      preLoaderRoute: typeof PastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$roomId': {
      id: '/join/$roomId'
      path: '/join/$roomId'
      fullPath: '/join/$roomId'
      preLoaderRoute: typeof JoinRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId_/matches': {
      id: '/rooms/$roomId_/matches'
      path: '/rooms/$roomId/matches'
      fullPath: '/rooms/$roomId/matches'
      preLoaderRoute: typeof RoomsRoomIdMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/rooms/new': {
      id: '/organizer/rooms/new'
      path: '/organizer/rooms/new'
      fullPath: '/organizer/rooms/new'
      preLoaderRoute: typeof OrganizerRoomsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId_/matches_/print': {
      id: '/rooms/$roomId_/matches_/print'
      path: '/rooms/$roomId/matches/print'
      fullPath: '/rooms/$roomId/matches/print'
      preLoaderRoute: typeof RoomsRoomIdMatchesPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PastRoute: PastRoute,
  SignupRoute: SignupRoute,
  JoinRoomIdRoute: JoinRoomIdRoute,
  RCodeRoute: RCodeRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  OrganizerRoomsNewRoute: OrganizerRoomsNewRoute,
  RoomsRoomIdMatchesRoute: RoomsRoomIdMatchesRoute,
  RoomsRoomIdMatchesPrintRoute: RoomsRoomIdMatchesPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
