/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PastRouteImport } from './routes/past'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GameRouteImport } from './routes/game'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms/$roomId'
import { Route as ReleaseIdRouteImport } from './routes/release.$id'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as JoinRoomIdRouteImport } from './routes/join.$roomId'
import { Route as GameRainRouteImport } from './routes/game_.rain'
import { Route as GameFlickRouteImport } from './routes/game_.flick'
import { Route as GameFlapRouteImport } from './routes/game_.flap'
import { Route as GameCoinRouteImport } from './routes/game_.coin'
import { Route as RoomsRoomIdMatchesRouteImport } from './routes/rooms/$roomId_.matches'
import { Route as OrganizerRoomsNewRouteImport } from './routes/organizer/rooms.new'
import { Route as RoomsRoomIdMatchesPrintRouteImport } from './routes/rooms/$roomId_.matches_.print'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PastRoute = PastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleaseIdRoute = ReleaseIdRouteImport.update({
  id: '/release/$id',
  path: '/release/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoomIdRoute = JoinRoomIdRouteImport.update({
  id: '/join/$roomId',
  path: '/join/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRainRoute = GameRainRouteImport.update({
  id: '/game_/rain',
  path: '/game/rain',
  getParentRoute: () => rootRouteImport,
} as any)
const GameFlickRoute = GameFlickRouteImport.update({
  id: '/game_/flick',
  path: '/game/flick',
  getParentRoute: () => rootRouteImport,
} as any)
const GameFlapRoute = GameFlapRouteImport.update({
  id: '/game_/flap',
  path: '/game/flap',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCoinRoute = GameCoinRouteImport.update({
  id: '/game_/coin',
  path: '/game/coin',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdMatchesRoute = RoomsRoomIdMatchesRouteImport.update({
  id: '/rooms/$roomId_/matches',
  path: '/rooms/$roomId/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoomsNewRoute = OrganizerRoomsNewRouteImport.update({
  id: '/organizer/rooms/new',
  path: '/organizer/rooms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdMatchesPrintRoute = RoomsRoomIdMatchesPrintRouteImport.update({
  id: '/rooms/$roomId_/matches_/print',
  path: '/rooms/$roomId/matches/print',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/past': typeof PastRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/game/coin': typeof GameCoinRoute
  '/game/flap': typeof GameFlapRoute
  '/game/flick': typeof GameFlickRoute
  '/game/rain': typeof GameRainRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/r/$code': typeof RCodeRoute
  '/release/$id': typeof ReleaseIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/organizer/rooms/new': typeof OrganizerRoomsNewRoute
  '/rooms/$roomId/matches': typeof RoomsRoomIdMatchesRoute
  '/rooms/$roomId/matches/print': typeof RoomsRoomIdMatchesPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/past': typeof PastRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/game/coin': typeof GameCoinRoute
  '/game/flap': typeof GameFlapRoute
  '/game/flick': typeof GameFlickRoute
  '/game/rain': typeof GameRainRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/r/$code': typeof RCodeRoute
  '/release/$id': typeof ReleaseIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/organizer/rooms/new': typeof OrganizerRoomsNewRoute
  '/rooms/$roomId/matches': typeof RoomsRoomIdMatchesRoute
  '/rooms/$roomId/matches/print': typeof RoomsRoomIdMatchesPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/past': typeof PastRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/game_/coin': typeof GameCoinRoute
  '/game_/flap': typeof GameFlapRoute
  '/game_/flick': typeof GameFlickRoute
  '/game_/rain': typeof GameRainRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/r/$code': typeof RCodeRoute
  '/release/$id': typeof ReleaseIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/organizer/rooms/new': typeof OrganizerRoomsNewRoute
  '/rooms/$roomId_/matches': typeof RoomsRoomIdMatchesRoute
  '/rooms/$roomId_/matches_/print': typeof RoomsRoomIdMatchesPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/game'
    | '/login'
    | '/past'
    | '/privacy'
    | '/releases'
    | '/signup'
    | '/terms'
    | '/game/coin'
    | '/game/flap'
    | '/game/flick'
    | '/game/rain'
    | '/join/$roomId'
    | '/r/$code'
    | '/release/$id'
    | '/rooms/$roomId'
    | '/organizer/rooms/new'
    | '/rooms/$roomId/matches'
    | '/rooms/$roomId/matches/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/game'
    | '/login'
    | '/past'
    | '/privacy'
    | '/releases'
    | '/signup'
    | '/terms'
    | '/game/coin'
    | '/game/flap'
    | '/game/flick'
    | '/game/rain'
    | '/join/$roomId'
    | '/r/$code'
    | '/release/$id'
    | '/rooms/$roomId'
    | '/organizer/rooms/new'
    | '/rooms/$roomId/matches'
    | '/rooms/$roomId/matches/print'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/game'
    | '/login'
    | '/past'
    | '/privacy'
    | '/releases'
    | '/signup'
    | '/terms'
    | '/game_/coin'
    | '/game_/flap'
    | '/game_/flick'
    | '/game_/rain'
    | '/join/$roomId'
    | '/r/$code'
    | '/release/$id'
    | '/rooms/$roomId'
    | '/organizer/rooms/new'
    | '/rooms/$roomId_/matches'
    | '/rooms/$roomId_/matches_/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GameRoute: typeof GameRoute
  LoginRoute: typeof LoginRoute
  PastRoute: typeof PastRoute
  PrivacyRoute: typeof PrivacyRoute
  ReleasesRoute: typeof ReleasesRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  GameCoinRoute: typeof GameCoinRoute
  GameFlapRoute: typeof GameFlapRoute
  GameFlickRoute: typeof GameFlickRoute
  GameRainRoute: typeof GameRainRoute
  JoinRoomIdRoute: typeof JoinRoomIdRoute
  RCodeRoute: typeof RCodeRoute
  ReleaseIdRoute: typeof ReleaseIdRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  OrganizerRoomsNewRoute: typeof OrganizerRoomsNewRoute
  RoomsRoomIdMatchesRoute: typeof RoomsRoomIdMatchesRoute
  RoomsRoomIdMatchesPrintRoute: typeof RoomsRoomIdMatchesPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past': {
      id: '/past'
      path: '/past'
      fullPath: '/past'
      preLoaderRoute: typeof PastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/release/$id': {
      id: '/release/$id'
      path: '/release/$id'
      fullPath: '/release/$id'
      preLoaderRoute: typeof ReleaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$roomId': {
      id: '/join/$roomId'
      path: '/join/$roomId'
      fullPath: '/join/$roomId'
      preLoaderRoute: typeof JoinRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game_/rain': {
      id: '/game_/rain'
      path: '/game/rain'
      fullPath: '/game/rain'
      preLoaderRoute: typeof GameRainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game_/flick': {
      id: '/game_/flick'
      path: '/game/flick'
      fullPath: '/game/flick'
      preLoaderRoute: typeof GameFlickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game_/flap': {
      id: '/game_/flap'
      path: '/game/flap'
      fullPath: '/game/flap'
      preLoaderRoute: typeof GameFlapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game_/coin': {
      id: '/game_/coin'
      path: '/game/coin'
      fullPath: '/game/coin'
      preLoaderRoute: typeof GameCoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId_/matches': {
      id: '/rooms/$roomId_/matches'
      path: '/rooms/$roomId/matches'
      fullPath: '/rooms/$roomId/matches'
      preLoaderRoute: typeof RoomsRoomIdMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/rooms/new': {
      id: '/organizer/rooms/new'
      path: '/organizer/rooms/new'
      fullPath: '/organizer/rooms/new'
      preLoaderRoute: typeof OrganizerRoomsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId_/matches_/print': {
      id: '/rooms/$roomId_/matches_/print'
      path: '/rooms/$roomId/matches/print'
      fullPath: '/rooms/$roomId/matches/print'
      preLoaderRoute: typeof RoomsRoomIdMatchesPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GameRoute: GameRoute,
  LoginRoute: LoginRoute,
  PastRoute: PastRoute,
  PrivacyRoute: PrivacyRoute,
  ReleasesRoute: ReleasesRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  GameCoinRoute: GameCoinRoute,
  GameFlapRoute: GameFlapRoute,
  GameFlickRoute: GameFlickRoute,
  GameRainRoute: GameRainRoute,
  JoinRoomIdRoute: JoinRoomIdRoute,
  RCodeRoute: RCodeRoute,
  ReleaseIdRoute: ReleaseIdRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  OrganizerRoomsNewRoute: OrganizerRoomsNewRoute,
  RoomsRoomIdMatchesRoute: RoomsRoomIdMatchesRoute,
  RoomsRoomIdMatchesPrintRoute: RoomsRoomIdMatchesPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
